# Server settings
server:
  port: 8000
# SPRING PROFILES
spring:
  application: eureka-server
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
  client:
    register-with-eureka: false
    fetch-registry: false
    